import type { Metadata } from "next";
import "./globals.css";
import heroImg from "@/assets/hero-image.jpg";
import Logo from "@/assets/Logo.svg";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-auto overflow-hidden dark">
      <body className="mx-auto h-full max-w-screen-xl overflow-x-hidden">
        <div className="flex flex-col">
          <figure className="relative h-[200px] w-full">
            <Image
              alt="logo image"
              src={Logo}
              className="absolute left-1/2 top-[20px] -translate-x-1/2"
              width={150}
            />
            <Image
              alt="hero image"
              src={heroImg}
              className="h-full object-cover"
            />
          </figure>

          {children}
        </div>
      </body>
    </html>
  );
}
