import type { Metadata } from "next";
import "./globals.css";
import heroImg from '@/assets/hero-image.jpg'
import Logo from '@/assets/Logo.svg'
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto">

        <div className="flex flex-col ">


          <figure className="w-full h-[200px] relative">
            <Image alt="logo image" src={Logo}  className="absolute top-[20px] left-1/2  -translate-x-1/2 " width={150}/>
            <Image alt="hero image" src={heroImg} className="h-full object-cover"/>

          </figure>

        {children}
        </div>
        
      </body>
    </html>
  );
}
